### ISSUE TITLE
资源里的视频没有封面，封面会单独变成一块资源

### ISSUE THREAD

**Issue by yebing233** [Bakabase/InsideWorld#100]
可播放文件查找器用的是默认的视频文件查找器 但是同步媒体库后出现的视频没有封面，而封面图会新生成一块资源 我的文件夹格式如下
![问题](https://user-images.githubusercontent.com/74483828/154847985-9289d82e-b8d2-4bcb-b5fa-dc6567b0daa9.jpg)

**Comment by yebing233** [comment]
可播放文件查找器用的是默认的视频文件查找器 但是同步媒体库后出现的视频没有封面，而封面图会新生成一块资源 我的文件夹格式如下
![问题](https://user-images.githubusercontent.com/74483828/154847985-9289d82e-b8d2-4bcb-b5fa-dc6567b0daa9.jpg)

**Comment by yebing233** [comment]
所有同步出来的视频都是这样，视频没有预览图，预览图会变成一块资源

**Comment by anobaka** [comment]
从你发的文件目录结构来看，需要将媒体库根目录设置为
```
{作者名文件夹}/2018年
{作者名文件夹}/2019年
...
```

**Comment by yebing233** [comment]
> 从你发的文件目录结构来看，需要将媒体库根目录设置为
> 
> ```
> {作者名文件夹}/2018年
> {作者名文件夹}/2019年
> ...
> ```

加了qq群一直没有动静我就来这里提问了
现在解决了，感谢

**Comment by anobaka** [comment]
不客气~
Github和Q群都可以提问哈，我看到了会第一时间回复~
