### ISSUE TITLE
系统信息里的文件位置可以更改目录吗

### ISSUE THREAD

**Issue by yebing233** [Bakabase/InsideWorld#101]
我想把他的数据全部搬到我的移动硬盘里

**Comment by anobaka** [comment]
暂时不支持，目前有这些文件占用空间不大，如果要多设备共享的话在新设备重新创建一次分类和媒体库即可
| 目录 | 说明 |
| :-- | :-- |
| 数据 | 所有本地数据，分类、媒体库、资源等 |
| 日志 | 最多保留14天内的数据，最多占用10g空间 |
| 更新器 | <100m |
| 备份路径 | 每次版本升级均会对上一个版本的数据进行一次备份，一般不会超过100m/次，确定数据无误后可删除 |

**Comment by yebing233** [comment]
好的 感谢

**Comment by anobaka** [comment]
@yebing233 现已支持 https://github.com/Bakabase/InsideWorld/issues/109
